// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Group struct {
	GroupsID int32
	Name     string
	Website  sql.NullString
}

type Link struct {
	AccountID   int64
	VtubersID   uuid.UUID
	PlatformsID int32
}

type Platform struct {
	PlatformsID int32
	Name        string
	UriTemplate string
}

type Vtuber struct {
	VtubersID   uuid.UUID
	GroupsID    sql.NullInt32
	NameDefault string
	NameEn      sql.NullString
	NameJp      sql.NullString
	NameCn      sql.NullString
	Bio         sql.NullString
	Languages   []string
	DebutDate   sql.NullTime
	Gender      sql.NullString
}
