// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	GroupsID int32
	Name     string
	Website  pgtype.Text
}

type Link struct {
	AccountID   int64
	VtubersID   pgtype.UUID
	PlatformsID int32
}

type Platform struct {
	PlatformsID int32
	Name        string
	UriTemplate string
}

type Vtuber struct {
	VtubersID   pgtype.UUID
	GroupsID    pgtype.Int4
	NameDefault string
	NameEn      pgtype.Text
	NameJp      pgtype.Text
	NameCn      pgtype.Text
	Bio         pgtype.Text
	Languages   []string
	DebutDate   pgtype.Date
	Gender      pgtype.Text
}
